// The 13 toybox items as legible string-grid pixel art, 24×24 per item.
// Same DNA as pets/sprites.js: each grid row is 24 chars, '.' = transparent,
// letters map to that item's palette. Rendered to offscreen canvases at runtime.
// If you touch these: rasterize and LOOK before shipping (scripts/render_items).

export const ITEM_SIZE = 24;

const OUT = '#241e3d'; // shared outline/dark

export const SPRITES = {
  // ── bharatanatyam: ghungroo ankle bells on a red strap ──
  ghungroo: {
    pal: { K: OUT, R: '#c04a4a', r: '#8f3535', G: '#e8c25a', g: '#b28a2e', W: '#f7ecc9' },
    grid: [
      '........................',
      '........................',
      '....RRRRRRRRRRRRRRRR....',
      '...RRRRRRRRRRRRRRRRRR...',
      '...RRrrrrrrrrrrrrrrRR...',
      '...RR..............RR...',
      '...RR..............RR...',
      '..KGGK..KGGK..KGGK..K...',
      '..GGGG..GGGG..GGGG......',
      '..GWGG..GWGG..GWGG......',
      '..GGgg..GGgg..GGgg......',
      '...gg....gg....gg.......',
      '........................',
      '....RRRRRRRRRRRRRRRR....',
      '...RRRRRRRRRRRRRRRRRR...',
      '...RRrrrrrrrrrrrrrrRR...',
      '...RR..............RR...',
      '..KGGK..KGGK..KGGK..K...',
      '..GGGG..GGGG..GGGG......',
      '..GWGG..GWGG..GWGG......',
      '..GGgg..GGgg..GGgg......',
      '...gg....gg....gg.......',
      '........................',
      '........................',
    ],
  },

  // ── carnatic: tanpura, long neck + round gourd ──
  tanpura: {
    pal: { K: OUT, N: '#8a5c3f', n: '#6b4630', B: '#c98f5e', b: '#a06f42', W: '#efd9b8', S: '#f4f2fb' },
    grid: [
      '..........KKK...........',
      '.........KNNNK..........',
      '.........KNWNK..........',
      '..........NNN...........',
      '..........NnN...........',
      '..........NnN...........',
      '..........NnN...........',
      '..........NnN...........',
      '..........NnN...........',
      '..........NnN...........',
      '..........NnN...........',
      '..........NnN...........',
      '.........BNnNB..........',
      '.......BBBNnNBBB........',
      '......BBBBNnNBBBB.......',
      '.....BBBBBSSSBBBBB......',
      '.....BBBbbSSSbbBBB......',
      '.....BBBbbbbbbbBBB......',
      '.....BBBBbbbbbBBBB......',
      '......BBBBbbbBBBB.......',
      '.......BBBBBBBBB........',
      '........BBBBBBB.........',
      '..........BBB...........',
      '........................',
    ],
  },

  // ── guitar: acoustic, neck up ──
  guitar: {
    pal: { K: OUT, N: '#6b4630', B: '#d99f6e', b: '#b5754a', W: '#efd9b8', S: '#f4f2fb' },
    grid: [
      '.........KKKK...........',
      '.........KWWK...........',
      '.........KWWK...........',
      '..........NN............',
      '..........NN............',
      '..........NN............',
      '..........NN............',
      '..........NN............',
      '..........NN............',
      '........BBNNBB..........',
      '.......BBBNNBBB.........',
      '.......BBBBBBBB.........',
      '........BBBBBB..........',
      '.......BBBBBBBB.........',
      '......BBBKKKKBBB........',
      '.....BBBKKKKKKBBB.......',
      '.....BBBKKKKKKBBB.......',
      '.....BBbbKKKKbbBB.......',
      '.....BBbbbbbbbbBB.......',
      '......BBbbbbbbBB........',
      '.......BBBbbBBB.........',
      '........BBBBBB..........',
      '........................',
      '........................',
    ],
  },

  // ── tennis: racket + ball ──
  tennis: {
    pal: { K: OUT, F: '#b99be8', f: '#8f74c2', S: '#e9e4f7', H: '#8a5c3f', A: '#d9f24e', a: '#aebf3a', W: '#f4f2fb' },
    grid: [
      '.........FFFFFF.........',
      '.......FFFFFFFFFF.......',
      '......FFSSSSSSSSFF......',
      '.....FFSSSSSSSSSSFF.....',
      '.....FSSSSSSSSSSSSF.....',
      '....FFSSSSSSSSSSSSFF....',
      '....FSSSSSSSSSSSSSSF....',
      '....FSSSSSSSSSSSSSSF....',
      '....FFSSSSSSSSSSSSFF....',
      '.....FSSSSSSSSSSSSF.....',
      '.....FFSSSSSSSSSSFF.....',
      '......FFSSSSSSSSFF......',
      '.......FFFFFFFFFF.......',
      '.........FfFFfF.........',
      '..........HHHH..........',
      '..........HHHH..........',
      '..........HHHH..........',
      '..AAAA....HHHH..........',
      '.AAAAAA...HHHH..........',
      '.AAWAAA...HHHH..........',
      '.AAAAAa...HHHH..........',
      '.AaAAAa.................',
      '..aaaa..................',
      '........................',
    ],
  },

  // ── table tennis: paddle + ball ──
  paddle: {
    pal: { K: OUT, R: '#e0645c', r: '#b34a44', H: '#c98f5e', h: '#a06f42', W: '#f4f2fb', w: '#d8d4e8' },
    grid: [
      '........................',
      '......RRRRRRRR..........',
      '....RRRRRRRRRRRR........',
      '...RRRRRRRRRRRRRR.......',
      '..RRRRRRRRRRRRRRRR......',
      '..RRRRRRRRRRRRRRRR......',
      '.RRRRRRRRRRRRRRRRRR.....',
      '.RRRRRRRRRRRRRRRRRR.....',
      '.RRRRRRRRRRRRRRRRRR.....',
      '.RRRrrRRRRRRRRRRRRR.....',
      '..RRrrrrRRRRRRRRRR......',
      '..RRRrrrrrrRRRRRRR......',
      '...RRRrrrrrrrrRRR.......',
      '....RRRRrrrrrrRR........',
      '......RRRRRRRR..........',
      '........HHHH............',
      '........HhHH............',
      '........HhHH.....WWW....',
      '........HhHH....WWWWW...',
      '........HhHH....WWwWW...',
      '........HHHH....WWWwW...',
      '.................WWW....',
      '........................',
      '........................',
    ],
  },

  // ── swimming: goggles ──
  goggles: {
    pal: { K: OUT, T: '#7fe9de', t: '#4fb3a9', R: '#3a3554', r: '#565177', W: '#f4f2fb' },
    grid: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      'rr..................rr..',
      'rrr................rrr..',
      '..rRRRRRRRr..rRRRRRRr...',
      '..RRRRRRRRR..RRRRRRRR...',
      '.RRTTTTTTRRRRRRTTTTTTRR.',
      '.RTTWTTTTTRrrRTTWTTTTTR.',
      '.RTTTTTTTTRrrRTTTTTTTTR.',
      '.RTtTTTTtTRRRRRTtTTTTtR.',
      '.RRTttttTRR..RRTttttTRR.',
      '..RRRRRRRR....RRRRRRRR..',
      '...RRRRRR......RRRRRR...',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },

  // ── horse riding: horse head, knight profile ──
  horse: {
    pal: { K: OUT, B: '#b5754a', b: '#8f5836', M: '#5a3b2a', W: '#f4f2fb', E: '#241e3d' },
    grid: [
      '........................',
      '.......KK...KK..........',
      '......KBBK.KBBK.........',
      '......KBBBKBBBK.........',
      '.....KBBBBBBBBMM........',
      '....KBBBBBBBBBMMM.......',
      '...KBBBBEBBBBBBMMM......',
      '..KBBBBBBBBBBBBBMMM.....',
      '..KBBBBBBBBBBBBBBMM.....',
      '.KBBBBBBBBBBBBBBBMMM....',
      '.KBBWBBBBBBBBBBBBMMM....',
      '.KBBBBBBBBBBBBBBBBMM....',
      '..KBBBBBBBBBBBBBBBMM....',
      '...KKBBBBBBBBBBBBBMM....',
      '......KBBBBBBBBBBMMM....',
      '.......BBBBBBBBBBMM.....',
      '.......BBBBBBBBBBBM.....',
      '......BBBBBBBBBBBBB.....',
      '......BBBBBBBBBBBBB.....',
      '.....BBBBBBBBBBBBBB.....',
      '.....BBBBBBBBBBBBBB.....',
      '.....bbbbbbbbbbbbbb.....',
      '........................',
      '........................',
    ],
  },

  // ── cycling: bicycle side view ──
  bicycle: {
    pal: { K: OUT, T: '#c9c4de', t: '#8d87ad', F: '#7fe9de', f: '#4fb3a9', S: '#f4f2fb' },
    grid: [
      '........................',
      '........................',
      '........................',
      '........................',
      '.......SS......SS.......',
      '.......FF......SS.......',
      '........FF....FF........',
      '........FF...FF.........',
      '.........FF..FF.........',
      '.........FFFFF..........',
      '....TTT...FFF...TTT.....',
      '...TTtTT..FFF..TTtTT....',
      '..TT...TT.F.F.TT...TT...',
      '..TT...TTFF.FFTT...TT...',
      '.TT.....TF...FT.....TT..',
      '.TT.....TT...TT.....TT..',
      '.TT.....TT...TT.....TT..',
      '..TT...TT.....TT...TT...',
      '..TT...TT.....TT...TT...',
      '...TTtTT.......TTtTT....',
      '....TTT.........TTT.....',
      '........................',
      '........................',
      '........................',
    ],
  },

  // ── gym: dumbbell ──
  dumbbell: {
    pal: { K: OUT, P: '#3a3554', p: '#565177', B: '#8d87ad', W: '#c9c4de' },
    grid: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '..PPP..............PPP..',
      '..PPP..............PPP..',
      '..PpP....pp....pp..PpP..',
      '..PpP....pp....pp..PpP..',
      '..PpPppppppppppppppPpP..',
      '..PpPpBBBBBBBBBBBBpPpP..',
      '..PpPpBWBBBBBBBBBBpPpP..',
      '..PpPppppppppppppppPpP..',
      '..PpP....pp....pp..PpP..',
      '..PpP....pp....pp..PpP..',
      '..PPP..............PPP..',
      '..PPP..............PPP..',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },

  // ── driving: steering wheel ──
  wheel: {
    pal: { K: OUT, R: '#3a3554', r: '#565177', H: '#8d87ad', W: '#c9c4de', T: '#7fe9de' },
    grid: [
      '........................',
      '........RRRRRRRR........',
      '......RRRRRRRRRRRR......',
      '.....RRRrrrrrrrrRRR.....',
      '....RRr..........rRR....',
      '...RRr............rRR...',
      '...RR..............RR...',
      '..RRr..............rRR..',
      '..RR................RR..',
      '..RR................RR..',
      '..RR.....HHHHHH.....RR..',
      '..RRHHHHHHHHHHHHHHHHRR..',
      '..RRHHHHHHtTtHHHHHHHRR..',
      '..RR.....HHHHHH.....RR..',
      '..RR......HHHH......RR..',
      '..RRr.....HHHH.....rRR..',
      '...RR.....HHHH.....RR...',
      '...RRr....HHHH....rRR...',
      '....RRr...........rRR...',
      '.....RRRrrrrrrrrRRR.....',
      '......RRRRRRRRRRRR......',
      '........RRRRRRRR........',
      '........................',
      '........................',
    ],
  },

  // ── books: a stack of three ──
  book: {
    pal: { K: OUT, A: '#f2a97e', a: '#c77f56', B: '#7fe9de', b: '#4fb3a9', C: '#b99be8', c: '#8f74c2', P: '#f4f2fb' },
    grid: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '....CCCCCCCCCCCCCCPP....',
      '...CCCCCCCCCCCCCCCCPP...',
      '...CCcCCCCCCCCCCCCCPP...',
      '...CCCCCCCCCCCCCCCCPP...',
      '...ccccccccccccccccPP...',
      '..BBBBBBBBBBBBBBBBPP....',
      '..BBbBBBBBBBBBBBBBPP....',
      '..BBBBBBBBBBBBBBBBPP....',
      '..bbbbbbbbbbbbbbbbPP....',
      '....AAAAAAAAAAAAAAAAPP..',
      '...AAAAAAAAAAAAAAAAAPP..',
      '...AAaAAAAAAAAAAAAAAPP..',
      '...AAAAAAAAAAAAAAAAAPP..',
      '...aaaaaaaaaaaaaaaaaPP..',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },

  // ── art: painter's palette + brush ──
  palette: {
    pal: { K: OUT, B: '#d9c8a9', b: '#b3a284', T: '#7fe9de', O: '#f2a97e', L: '#b99be8', G: '#d9f24e', R: '#e0645c', H: '#8a5c3f', S: '#f4f2fb' },
    grid: [
      '..................SS....',
      '.................SHH....',
      '................HHH.....',
      '...............HHH......',
      '....BBBBBB....HHH.......',
      '..BBBBBBBBBB.HHH........',
      '.BBBBBBBBBBBHHH.........',
      '.BBTTBBBBBBBBB..........',
      'BBBTTBBBBBOOBBB.........',
      'BBBBBBBBBBOOBBBB........',
      'BBLLBBBBBBBBBBBB........',
      'BBLLBBBBBBBBGGBB........',
      'BBBBBBBBBBBBGGBB........',
      'BBBBRRBBBBBBBBBB........',
      'BBBBRRBBBBKKBBBB........',
      '.BBBBBBBBBKKKBBB........',
      '.BBBBBBBBBBKKBB.........',
      '..BBBBBBBBBBBBB.........',
      '...BBBBBBBBBBB..........',
      '.....BBBBBBBb...........',
      '.......bbbbb............',
      '........................',
      '........................',
      '........................',
    ],
  },

  // ── photography: camera ──
  camera: {
    pal: { K: OUT, B: '#3a3554', b: '#565177', L: '#c9c4de', l: '#8d87ad', T: '#7fe9de', t: '#4fb3a9', W: '#f4f2fb' },
    grid: [
      '........................',
      '........................',
      '........................',
      '........................',
      '....bbbb....LL..........',
      '....bbbb....LL..........',
      '..BBBBBBBBBBBBBBBBBBBB..',
      '..BBBBBBBBBBBBBBBBBBBB..',
      '..BBbbbbbbbbbbbbbbbbBB..',
      '..BB......llll......BB..',
      '..BB....llLLLLll....BB..',
      '..BB...lLLTTTTLLl...BB..',
      '..BB...lLTTWTTTLl...BB..',
      '..BB...lLTTTTTtLl...BB..',
      '..BB...lLTTTTttLl...BB..',
      '..BB...lLLttttLLl...BB..',
      '..BB....llLLLLll....BB..',
      '..BB......llll......BB..',
      '..BBbbbbbbbbbbbbbbbbBB..',
      '..BBBBBBBBBBBBBBBBBBBB..',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
};

export const ITEM_IDS = Object.keys(SPRITES);

/** Render one item to an offscreen canvas (1px per grid cell). */
export function buildItemSprite(id) {
  const def = SPRITES[id];
  const c = document.createElement('canvas');
  c.width = ITEM_SIZE;
  c.height = ITEM_SIZE;
  const ctx = c.getContext('2d');
  def.grid.forEach((row, y) => {
    for (let x = 0; x < ITEM_SIZE; x++) {
      const col = def.pal[row[x]];
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x, y, 1, 1);
    }
  });
  return c;
}
